# Generated by Django 3.2.6 on 2021-08-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="center_coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
