# Generated by Django 3.2.6 on 2021-08-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_center_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
