# Generated by Django 3.2.6 on 2021-08-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_alter_route_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
